behaviors:
  HiderAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: True
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 50000
    threaded: True

  SeekerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: True
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 50000
    threaded: True
