behaviors:
  Hide:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048  # Увеличение размера батча для лучшего использования GPU
      buffer_size: 40960  # Увеличение буфера для обработки большего объема данных
      learning_rate: 0.0001  # Снижение скорости обучения для более стабильного обучения
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5  # Увеличение числа эпох для более тщательной обработки данных
    network_settings:
      normalize: true
      hidden_units: 256  # Увеличение числа скрытых единиц для более сложных моделей
      num_layers: 3  # Увеличение числа слоев для более глубоких нейронных сетей
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 5000  # Уменьшение частоты суммаризации для более частого мониторинга
    threaded: true
